### PR TITLE
Django 2.0 support

### PR DESCRIPTION
**Pull request by lpomfrey**
Adds config to run tests on Python 3.6 and with Django 2.0 and removes the django<2.0 requirement.

### CODE REVIEW

**Comment by stephrdev** [comment]
Hi! Thank you for the contribution. Would you be so kind and drop the 3.3 tests? The remaining tests pass. As soon as we get this PR merged I'll prepare a release.

**Comment by lpomfrey** [comment]
Thanks for the quick response. I've dropped the 3.3 tests. It may be worth dropping the tests for the unsupported versions of Django as well, but I'll leave that decision to you.

**Comment by stephrdev** [comment]
I think we should keep them as long as they dont break. I'll update the setup.py too and prepare a relase today or tomorrow. Trying my best :-)

**Comment by lpomfrey** [comment]
OK, excellent, thanks.

**Pull request merged**
