### PR TITLE
Enable selection of caches on a per-job basis.

### PR DESCRIPTION
**Pull request by Kobold**
My use case for this PR is that I'd like some of my application's jobs to end up in an in-memory cache, and others to end up in the usual memcache. We also might end up using a super persistent disk-backed cache for a third group of jobs. This PR should give us the flexibility to do that.

I tried to cover docs and testing very thoroughly, but let me know if they need any additional work to get across the line. 

Again, love the library! Thanks!

### CODE REVIEW

**Comment by Kobold** [comment]
No idea why the tests are failing on earlier versions — looks like a `pytest_django` related regression?

**Comment by Kobold** [comment]
Kinks worked out. Ready for review @stephrdev , when you have a moment!

**Comment by stephrdev** [comment]
I really like this feature. There is another PR pending (#68) - I think we can merge both and release afterwards. Thank you!

**Comment by Kobold** [comment]
Thanks for taking a look. Yep, saw that PR!

Going forward, I presume you want to land #68 first. I'll handle merge conflicts once that's landed on master.

If you think #68 is going to be a awhile, I'm happy to handle the merge conflict on it that will result from landing this on master and pass it along to you — trying to minimize headache for you. :)

**Comment by stephrdev** [comment]
PR #68 landed in master. I prepeared everything for a 1.2 release and would be happy to get your changes in the release. Thank you very much for rebasing your PR against master!

**Comment by Kobold** [comment]
Ok, this is ready to merge.

Please give the tests a quick look to make sure you're happy with the coverage. I tried to make sure all the Is were dotted and Ts crossed with the new testing layout, but I'm not sure I got everything.

**Pull request merged**
