### PR TITLE
Bugfix in set method and adding raw_get method

### PR DESCRIPTION
**Pull request by thisisstephenbetts**
Hi there, 

we noticed that I'd created a small bug in my implementation of the `set` method — instead of using the `expiry` I'd used the `timeout`. 

In order to easily add a regression test, I also added a `raw_get` method, which has the same semantics as all the other methods, but just returns the raw contents of the cache (i.e., the expiry, value typle), and never triggers a refreshfetch. This method is helpful (though obviously not necessary) for checking that the correct expiry is used, but in general usage it allows us to check whether a value is in the cache at all. That (like the `set` method) can be useful for more active cache management.

If you are happy with these changes I will add some lines to the documentation for the `raw_get` method (and of course feel free to suggest a different name for that method).

Thanks very much. Yours,

Stephen.

### CODE REVIEW

**Comment by stephrdev** [comment]
Thank you for the bugfix.

Have you tested if stuff still works after changing the import / os.environ.set ordering? I'm not sure if importing of django.settings works before the DJANGO_SETTINGS_MODULE is set in sandbox files.

**Comment by thisisstephenbetts** [comment]
Hi there, 

the test suite passes, but I didn't try much else at that point. I only changed the ordering as the automatic Travis linting failed my original PR. I'm very happy to revert that commit — just as you like.

Thanks,

Stephen.

**Comment by thisisstephenbetts** [comment]
If the Travis checks are not critical I agree it's worthwhile reverting that last commit to keep this cleaner. I assumed (though perhaps should have thought it through a bit more) the Travis failures would be a blocker.

**Comment by stephrdev** [comment]
Well, broken builds on Travis are bad but I'm thinking about why are these changes nessesary. You just changed something one file and so many other things are now invalid? Is it maybe some version updates in isort or something like that? Just want to understand why they appear now.

**Comment by thisisstephenbetts** [comment]
Yeah, totally agree on understanding it now. I'm confused too. 

What I'll do is revert that commit and then see what Travis does with it this time, and try to get into the reasons a bit better. Thanks!

**Comment by thisisstephenbetts** [comment]
Okay, I reverted that commit and the checks are failing again. This is the error I'm seeing:
```
=================================== FAILURES ===================================
_________________________________ isort-check __________________________________
ERROR: /home/travis/build/codeinthehole/django-cacheback/cacheback/utils.py Imports are incorrectly sorted.
```
But, as you can see from the PR, I've not changed the imports at all. 

Please let me know what you think! Very happy to make whatever changes are needed.

(Also, if this is approved in principle I can add to the docs)

**Comment by stephrdev** [comment]
Hi Stephen, I just played around a bit and recognized that isort had some releases in the last days, including many hotfix releases. I think the now failing check on utils.py should be fixed and then I'm fine with merging the PR!

Thanks a lot for your patience and my many questions regarding the changes :-)

**Comment by thisisstephenbetts** [comment]
That's great — thanks very much @stephrdev! 

I've added a bit of documentation on the `raw_get` method.

Thank you!

**Comment by stephrdev** [comment]
Would you mind adding the missing blank line to cacheback/utils.py? Thanks!

**Comment by thisisstephenbetts** [comment]
Thanks @stephrdev — apologies, I didn't read the error carefully enough, and realise it was only a missing blank line that isort wanted. Thanks very much for your help.

**Pull request merged**
